# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Workflow Experiment

on:
  push:
    tags:
      - '*'

jobs:
  print-message:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print Hello Test
      run: echo "Hello Test"
